---
kind: Service
apiVersion: v1
metadata:
  name: demowebappservice
spec:
 selector:
   app: demowebapp
 ports:
   - protocol: "TCP"
     port: 8080
     targetPort: 80
     nodePort: 30002
 type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demowebapp
spec:
  replicas: 3
  template:
   metadata:
    labels:
     app: demowebapp
   spec:
    containers:
     - name: demowebapp
       image: demowebapp
       ports:
        - containerPort: 80
     