FROM maven:3.5-jdk-8-alpine AS build 
## Maintainer ##
MAINTAINER saguruja@cisco.com
WORKDIR /demowebapp
RUN mvn clean install

FROM openjdk:8-jre-alpine
WORKDIR /demowebapp
COPY --from=build /demowebapp/target/demowebapp.war ${CATALINA_HOME}/webapps/
CMD ${CATALINA_HOME}/bin/startup